### PR TITLE
Removes internal files used for swift demangling and replaces with package dependency on swift-demangling

### PR DESCRIPTION
**Pull request by atreat**
Updates to use Swift Demangling package instead of managing this dependency inside this repo.

### CODE REVIEW

**Review by ArielDemarco — APPROVED** [review]

**Comment by ArielDemarco** [comment]
Have you tried to compile on the other platforms? (watchOS / macOS / etc)

**Comment by atreat** [comment]
> Have you tried to compile on the other platforms? (watchOS / macOS / etc)


Good call, probably need to edit the Mac.xcworkspace and WatchOS.xcworkspace. Will confirm

**Comment by atreat** [comment]
Looks like the Mac.xcworkspace and WatchOs.xcworkspace don't compile even on `master`.

**Comment by ArielDemarco** [comment]
I expressed myself wrong: i'd check if this compiles on the different platforms we support on 6.x (like, integrating it with Embrace and check if it keeps working)

**Pull request closed without merging**
